#!/bin/bash

# Path to the directory where the files are located
directory="/glade/u/home/arezoo/wrf-hydro-training/example_case/FORCING"

# Loop through all files in the directory
for file in "$directory"/*; do
  # Check if the file matches the pattern YYYYMMDDHHMM.LDASIN_DOMAIN1
  if [[ "$file" =~ ([0-9]{8})([0-9]{2})([0-9]{2})\.LDASIN_DOMAIN1$ ]]; then
    # Extract the base part (YYYYMMDDHH)
    new_name="${BASH_REMATCH[1]}${BASH_REMATCH[2]}.LDASIN_DOMAIN1"

    # Rename the file
    mv "$file" "$directory/$new_name"
    echo "Renamed: $file -> $new_name"
  fi
done


